<div class="wrapper">
    <div class="container">
        <div class="result-block">
            <span>Result amount:</span>
            <span class="result-amount"></span>
        </div>
        <div class="history"></div>
        <ul class="menu">
            <li>
                <div>
                    <label for="amount" class="screenReader-only">Amount</label>
                    <?= $this->formText(
                        'amount',
                        1,
                        [
                            'id' => "amount",
                            'onfocus' => "if(this.value == '1') this.value='';",
                            'onblur' => "if(this.value == '') this.value='1'",
                            'maxlength' => "10",
                            'tabindex' => "1",
                            'required' => "required"
                        ]
                    ); ?>
                </div>
            </li>
            <li>
                <div>
                    <span id="fromInput">
                        <?= $this->formSelect(
                            'from-currency',
                            $this->defaultCurrency,
                            [
                                'class' => 'fromCurrency',
                                'tabindex' => "2",
                            ],
                            $this->currencyList
                        ); ?>
                    </span>
                    <span class="uccInverse"><button id="inverseBtn">↔</button></span>
                    <span id="toInput" class="">
                        <?= $this->formSelect(
                            'to-currency',
                            $this->defaultCurrency,
                            [
                                'class' => "toCurrency",
                                'tabindex' => "3",
                            ],
                            $this->currencyList
                        ); ?>
                    </span>
                </div>
            </li>
            <li>
                <div>
                    <button id="conver_go" class="uccGoButton" type="button" tabindex="5">Convert</button>
                </div>
            </li>
        </ul>
    </div>
</div>