<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Converter</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="<?= $this->baseUrl(); ?>/favicon.ico" type="image/x-icon">
        <link rel="stylesheet" href="<?= $this->baseUrl(); ?>/css/style.css" type="text/css" media="screen, projection"/>
        <script src="<?= $this->baseUrl(); ?>/js/jquery.js"></script>
        <script src="<?= $this->baseUrl(); ?>/js/script.js"></script>
    </head>
    <body>
        <?= $this->layout()->content; ?>
    </body>
</html>